# Generated by Django 5.1.2 on 2024-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("code", models.CharField(blank=True, max_length=5, null=True)),
                ("code_exp", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "db_table": "country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("title", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "language",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("title", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "notification_category",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                ("txt", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "notification_template",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=510, null=True)),
                ("address", models.CharField(blank=True, max_length=510, null=True)),
                ("started", models.DateTimeField()),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("archived", models.IntegerField()),
            ],
            options={
                "db_table": "project",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TranslationString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("translation_field_id", models.IntegerField(blank=True, null=True)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "translation_string",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("role_id", models.PositiveIntegerField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("verified", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.IntegerField()),
                ("status", models.IntegerField()),
                ("created", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_notification",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotificationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_id", models.IntegerField(blank=True, null=True)),
                ("txt", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "user_notification_option",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_notification", models.IntegerField()),
                ("push_notification", models.IntegerField()),
            ],
            options={
                "db_table": "user_notification_setting",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "user_role",
                "managed": False,
            },
        ),
    ]
